steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - fastapi-test
  - --runtime
  - python311
  - --region
  - asia-northeast1
  - --entry-point
  - entry_point
  env:
  - PLATFORM=GCP